[tools]
bat = "latest"
bottom = "latest"
cargo-binstall = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@openai/codex" = "latest"
delta = "latest"
dotnet = "10"
#"cargo:dotter" = "latest"
duf = "latest"
dust = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
"npm:@google/gemini-cli" = "latest"
gh = "latest"
jq = "latest"
"npm:@kilocode/cli" = "latest"
node = "24.13.1"
python = "latest"
ripgrep = "latest"
ruby = "3"
ruff = "latest"
rust = "latest"
"cargo:sheldon" = "latest"
starship = "latest"
"cargo:tre-command" = "latest"
usage = "latest"
uv = "latest"
xh = "latest"
yq = "latest"
zoxide = "latest"

[settings]

[settings.ruby]
compile = false
