[tools]
bat = "latest"
bottom = "latest"
cargo-binstall = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@openai/codex" = "latest"
delta = "latest"
dotnet = "10"
"npm:@google/gemini-cli" = "latest"
jq = "latest"
"npm:@kilocode/cli" = "latest"
node = "latest"
python = "latest"
ruby = "3"
rust = "latest"
"cargo:sheldon" = "latest"
"cargo:tre-command" = "latest"
usage = "latest"
yq = "latest"

[settings]

[settings.ruby]
compile = false
