if empty(glob("$XDG_CACHE_HOME/vim/undo"))
  silent !mkdir -p $XDG_CACHE_HOME/vim/undo
endif
set undodir=$XDG_CACHE_HOME/vim/undo
if empty(glob("$XDG_CACHE_HOME/vim/swap"))
  silent !mkdir -p $XDG_CACHE_HOME/vim/swap
endif
set directory=$XDG_CACHE_HOME/vim/swap
if empty(glob("$XDG_CACHE_HOME/vim/backup"))
  silent !mkdir -p $XDG_CACHE_HOME/vim/backup
endif
set backupdir=$XDG_CACHE_HOME/vim/backup
set viminfo+='1000,n$XDG_CACHE_HOME/vim/viminfo
set runtimepath=$XDG_CACHE_HOME/vim,$XDG_CACHE_HOME/vim/after,$VIMRUNTIME

let MRU_File = $XDG_CACHE_HOME . '/vim/mru_files'

if empty(glob("$XDG_CACHE_HOME/vim/autoload/plug.vim"))
  silent !curl -fLo $XDG_CACHE_HOME/vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Specify a directory for plugins
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin("$XDG_CACHE_HOME/vim/plugged")

" Make sure you use single quotes
" Declare the list of plugins.
Plug 'tpope/vim-sensible'
Plug 'arcticicestudio/nord-vim', { 'branch': 'develop' }
Plug '/usr/local/opt/fzf'
Plug 'vim-scripts/mru.vim'

" Initialize plugin system
call plug#end()

if empty(glob("$XDG_CACHE_HOME/vim/plugged/nord-vim/colors/nord.vim"))
  syntax on
else
  let g:nord_underline = 1
  colorscheme nord
endif
set number

" https://wiki.archlinux.jp/index.php/XDG_Base_Directory
" set runtimepath^=$XDG_CONFIG_HOME/vim
" set runtimepath+=$XDG_DATA_HOME/vim
" set runtimepath+=$XDG_CONFIG_HOME/vim/after
" set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
" set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after
" let g:netrw_home = $XDG_DATA_HOME."/vim"
" call mkdir($XDG_DATA_HOME."/vim/spell", 'p')
" set viewdir=$XDG_DATA_HOME/vim/view | call mkdir(&viewdir, 'p')
" set backupdir=$XDG_CACHE_HOME/vim/backup | call mkdir(&backupdir, 'p')
" set directory=$XDG_CACHE_HOME/vim/swap   | call mkdir(&directory, 'p')
" set undodir=$XDG_CACHE_HOME/vim/undo     | call mkdir(&undodir,   'p')
" if !has('nvim') | set viminfofile=$XDG_CACHE_HOME/vim/viminfo | endif
