# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins.zsh-defer]
github = 'romkatv/zsh-defer'
apply = ['source']

[plugins.compinit]
inline = 'autoload -Uz compinit && zsh-defer compinit'

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'
apply = ['defer']

[plugins.zsh-completions]
github = 'zsh-users/zsh-completions'
apply = ['defer']

[plugins.zsh-syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'
apply = ['defer']

[plugins.dotfiles-sh-defer]
local = '~/.dotfiles/.config/sh'
use = ['*.{z,*}sh']
apply = ['defer']

[plugins.dotfiles-sync]
local = '~/.dotfiles/.config/zsh/sync'
use = ['*.zsh']
apply = ['source']

[plugins.mise]
#inline = 'eval "$(mise activate zsh)"'
local = '~/.dotfiles/.config/zsh/mise'
apply = ['source']
#apply = ['defer']

# [plugins.mise-shims]
# #inline = 'eval "$(mise activate --shims)"'
# local = '~/.local/share/mise/shims'
# apply = ['PATH']

[plugins.starship]
# inline = 'eval "$(starship init zsh)"'
local = '~/.dotfiles/.config/zsh/starship'
# apply = ['defer']
apply = ['source']

[plugins.fzf]
# inline = 'eval "$(fzf --zsh)"'
local = '~/.dotfiles/.config/zsh/fzf'
apply = ['defer']

[plugins.zoxide]
# inline = 'eval "$(zoxide init zsh)"'
# inline = 'eval "$(zoxide init zsh --cmd cd)"'
local = '~/.dotfiles/.config/zsh/zoxide'
apply = ['defer']
