#!/bin/bash

## Options
if [ -n "$BASH" ]; then
  SHEXT_PREFIX=ba
  shopt -s extglob
elif [ -n "$ZSH_NAME" ]; then
  SHEXT_PREFIX=z
  setopt EXTENDED_GLOB
fi

## Functions
globexists() {
  # https://stackoverflow.com/questions/6363441/check-if-a-file-exists-with-a-wildcard-in-a-shell-script
  compgen -G "$1" >/dev/null || [ -e "$1" ]
}

## Main

# source /.config/bash-completion.d/*.*sh if it exists.
if globexists "$XDG_CONFIG_HOME"/bash-completion.d/*.*("$SHEXT_PREFIX")sh; then
  for f in "$XDG_CONFIG_HOME"/bash-completion.d/*.*("$SHEXT_PREFIX")sh; do
    # shellcheck disable=SC1090
    . "$f"
  done
fi
