# https://zenn.dev/kairkarigohan/articles/5b580a2f10b4ea
[helpers]

[default]
depends = []

[default.files]
".bash_aliases" = "~/.bash_aliases"
".bash_profile" = "~/.bash_profile"
# https://github.com/SuperCuber/dotter/wiki/Setup-and-Configuration#complex-target
# https://github.com/SuperCuber/dotter/issues/137#issuecomment-1656018017
".config" = { target = "~/.config", type = "symbolic", recurse = false }
".profile.d" = { target = "~/.profile.d", type = "symbolic", recurse = false }
".shellcheckrc" = "~/.shellcheckrc"
".zshenv" = "~/.zshenv"
"bin" = { target = "~/bin", type = "symbolic", recurse = false }
"local" = { target = "~/local", type = "symbolic", recurse = false }
"secret/.secret" = { target = "~/.secret", type = "symbolic", recurse = false }
"secret/.ssh" = { target = "~/.ssh", type = "symbolic", recurse = false }

# ".config/powershell/profile.ps1" = ""

[default.variables]

# [settings]
# default_target_type = "automatic"

# sudo apt -y install build-essential
# export MISE_CONFIG_DIR=${XDG_CONFIG_HOME:-$HOME/.config}/mise/${OSDIR:?}
# echo $MISE_CONFIG_DIR
# eval "$(mise activate ${SHELL##*/})"
# eval "$(mise completion ${SHELL##*/})"
# echo $PATH | tr : '\n'
# sudo mise self-update
# mise plugins update
# mise outdated
# mise list --global
# mise upgrade -y
# mise upgrade -y --bump # upgrade all new versions
# mise doctor
# mise use --global rust
# which -a cargo
# cargo install dotter
# which -a dotter
# cd ~/.dotfiles
# mv ~/.dotfiles/.dotter/global.toml{,.bak}
# dotter init
# mv ~/.dotfiles/.dotter/global.toml{.bak,}
# --
# includes = [".dotter/macos.toml"]
# packages = ["default", "dotfiles"]
# --
# dotter deploy -d
# dotter deploy -d --force
# dotter deploy
# dotter deploy --force
# ls -la ~
# dotter undeploy -d
# dotter undeploy -y  # not work on windows..
