[tools]
bat = "latest"
bottom = "latest"
delta = "latest"
duf = "latest"
dust = "latest"
eza = "latest"
fd = "latest"
ghq = "latest"
ripgrep = "latest"
ruby = "latest"
rust = "latest"
xh = "latest"
zoxide = "latest"
